version: "3.8"
networks:
  redis-net:



services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - redis-net
  rkiapi:
    image: marlon360/rki-covid-server:v2
    container_name: rkiapi
    #build:
    #  context: rki-covid-api-2/docker
    ports:
      - "9095:3000"
    depends_on:
      - redis
    environment:
      - REDISHOST=redis
    networks:
      - redis-net


  jupyterds2:
    image: jupyterds2
    container_name: jupyterds2
    build:
      context: .
    ports:
      - 9096:8888 
    volumes:
      - ${PWD}:/home/jovyan/work
    depends_on:
      - rkiapi
    links:
      - "rkiapi:rkiapi"
    networks:
      - redis-net
    #environment:
    #  - JUPYTER_TOKEN='jupyter'
    #  - PASSWORD='jupyter'
  
  visuds2:
    image: visuds2
    container_name: visuds2
    build:
      context: .
    ports:
      - 9097:3016 
    volumes:
      - ${PWD}/generated/:/usr/src/app
    depends_on:
      - jupyterds2
    links:
      - "jupyterds2:jupyterds2"
      - "dataservds2:dataservds2"
    networks:
      - redis-net
    #environment:
    #  - JUPYTER_TOKEN='jupyter'
    #  - PASSWORD='jupyter'
  
  dataservds2:
    image: dataservds2
    container_name: dataservds2
    build:
      context: ./data_server
    ports:
      - 9098:3017 
    volumes:
      - ${PWD}/generated/:/usr/src/app/public/visualisation_files/generated
    depends_on:
      - jupyterds2
    links:
      - "jupyterds2:jupyterds2"
    networks:
      - redis-net
    #environment:
    #  - JUPYTER_TOKEN='jupyter'
    #  - PASSWORD='jupyter'
  




